---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)
library(p8105.datasets)
```

```{r}
rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")

```


```{r}
data("nyc_airbnb")
nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>% 
  filter(
    neighbourhood_group == "Manhattan", 
    room_type == "Entire home/apt", 
    price %in% 100:500 
  ) 
```
Column {data-width=650}
-----------------------------------------------------------------------
### Chart A

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price, "\nStars: ", stars)
  ) %>% 
  plot_ly(
    x = ~ lat, 
    y = ~ long, 
    type = "scatter", 
    mode = "markers", 
    color = ~ price, alpha = 0.5, 
    text = ~ text_label) 
```

Column {data-width=350}
-----------------------------------------------------------------------
### Chart B

```{r}
nyc_airbnb %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~ price, color = ~ neighbourhood, 
          type = "box", colors = "viridis")
```

### Chart C

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

